### ISSUE TITLE
Data type not supported

### ISSUE THREAD

**Issue by xiaoxi0xiaoxi** [XUJiahua/metabase-impala-driver#1]
Hello,
The following error occurs when I use the time query filter for a certain time range.
:error "[Cloudera]JDSI Data type not supported: 2014",
:stacktrace
["com.cloudera.impala.dsi.dataengine.utilities.TypeMetadata.createTypeMetadata(Unknown Source)"
"com.cloudera.impala.utilities.conversion.TypeConverter.toType(Unknown Source)"
"com.cloudera.impala.jdbc.common.SPreparedStatement.setObject(Unknown Source)"
"com.cloudera.impala.jdbc.common.SPreparedStatement.setObject(Unknown Source)"
"com.cloudera.impala.hivecommon.jdbc42.Hive42PreparedStatement.setObject(Unknown Source)"

The request parameters are as follows:
{"parameters":[{"type":"date/all-options","value":"2021-06-07~2021-06-09","target":["dimension",["field","event_dt_utc8_time",{"base-type":"type/DateTime"}]]}]}

**Comment by jixiang-wang** [comment]
> Hello, The following error occurs when I use the time query filter for a certain time range. :error "[Cloudera]JDSI Data type not supported: 2014", :stacktrace ["com.cloudera.impala.dsi.dataengine.utilities.TypeMetadata.createTypeMetadata(Unknown Source)" "com.cloudera.impala.utilities.conversion.TypeConverter.toType(Unknown Source)" "com.cloudera.impala.jdbc.common.SPreparedStatement.setObject(Unknown Source)" "com.cloudera.impala.jdbc.common.SPreparedStatement.setObject(Unknown Source)" "com.cloudera.impala.hivecommon.jdbc42.Hive42PreparedStatement.setObject(Unknown Source)"
> 
> The request parameters are as follows: {"parameters":[{"type":"date/all-options","value":"2021-06-07~2021-06-09","target":["dimension",["field","event_dt_utc8_time",{"base-type":"type/DateTime"}]]}]}

Hello, is this problem now solved?

**Comment by XUJiahua** [comment]
You could try to debug like the following.

![image](https://user-images.githubusercontent.com/1501598/135383520-83d38302-45e4-42a8-9106-52f55125bb21.png)

Previous query will be translated to the following:

![image](https://user-images.githubusercontent.com/1501598/135383825-b2dc3842-88ff-40e8-80db-c5758e7f4424.png)

Then check if your translated SQL statement meets Impala SQL sytanx. 

BTW, I'm currently using Metabase 0.35.4.

**Comment by XUJiahua** [comment]
Found the issue! I forgot to upload the compiled jar after fixing.
Please use https://github.com/XUJiahua/metabase-impala-driver/releases/tag/v1.0.1-SNAPSHOT-2.6.17 .
