### ISSUE TITLE
大佬，有遇到这个问题

### ISSUE THREAD

**Issue by jixiang-wang** [XUJiahua/metabase-impala-driver#2]
https://discourse.metabase.com/t/date-variables-doesnt-work/16578

**Comment by XUJiahua** [comment]
是不是与 Metabase 的版本不兼容了，我现在用的 0.35.4

**Comment by XUJiahua** [comment]
![image](https://user-images.githubusercontent.com/1501598/135382467-409251a5-40e0-4625-bf8b-8e6fc1488e9f.png)
我这是这样的

**Comment by jixiang-wang** [comment]
> ![image](https://user-images.githubusercontent.com/1501598/135382467-409251a5-40e0-4625-bf8b-8e6fc1488e9f.png) 我这是这样的

你好，我刚才重新下载了v0.35版本的jar文件
下载地址：https://www.metabase.com/docs/v0.35
然后用了你这里的impala-driver，还是不行，一样报错，方便加个联系方式吗？

**Comment by XUJiahua** [comment]
不好意思，1.0.0版本后有代码更新，忘记上传 jar 包了。。。 😭 
请使用这个版本：https://github.com/XUJiahua/metabase-impala-driver/releases/tag/v1.0.1-SNAPSHOT-2.6.17

v0.35.4 下载地址：https://downloads.metabase.com/v0.35.4/metabase.jar
我这使用 Metabase 的项目工程上好久没更新了，在 v0.35.4 下日常使用很稳定。

v0.40.5 下初步试了下，貌似能用，不敢保证。

**Comment by jixiang-wang** [comment]
刚刚试了下，好像是可以的，非常感谢，国庆快乐

**Comment by XUJiahua** [comment]
国庆快乐 :)
