### ISSUE TITLE
Join across multiple databases

### ISSUE THREAD

**Issue by jixiang-wang** [XUJiahua/metabase-impala-driver#3]
Can it be achieved?

**Comment by XUJiahua** [comment]
yes, just have a try first
![image](https://user-images.githubusercontent.com/1501598/136533321-21d95919-d982-43ae-9fad-e07f68a685a4.png)

**Comment by jixiang-wang** [comment]
> yes, just have a try first ![image](https://user-images.githubusercontent.com/1501598/136533321-21d95919-d982-43ae-9fad-e07f68a685a4.png)

no, I want to join impala and mysql

**Comment by XUJiahua** [comment]
As far as I know, it's impossible. You'd better ask Metabase for help.
